//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SES.CMS {
    
    
    public partial class Default {
        
        /// <summary>
        /// uc1TopAdv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucTopAdvertisment uc1TopAdv;
        
        /// <summary>
        /// uc8HomeSlide control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucHomeSlide uc8HomeSlide;
        
        /// <summary>
        /// uc10ucDanhMucNoiBat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucDanhMucNoiBat uc10ucDanhMucNoiBat;
        
        /// <summary>
        /// uc3ThamKhaoGiaXa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucThamKhaoGiaXe uc3ThamKhaoGiaXa;
        
        /// <summary>
        /// uc9TuVanAndKyThuat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucTuVanAndKyThuat uc9TuVanAndKyThuat;
        
        /// <summary>
        /// ltrNgay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrNgay;
        
        /// <summary>
        /// uc2lastestnews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucLastestNews uc2lastestnews;
        
        /// <summary>
        /// uc13UcTopContactInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucTopContactInfo uc13UcTopContactInfo;
        
        /// <summary>
        /// uc4TopRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucTopRightAdv uc4TopRight;
        
        /// <summary>
        /// uc5MiddleAdv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucMiddleAdv uc5MiddleAdv;
        
        /// <summary>
        /// uc6Main control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucMainHomePageCategory uc6Main;
        
        /// <summary>
        /// uc7ucMostRead control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucMostRead uc7ucMostRead;
        
        /// <summary>
        /// uc14ucSaleOff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::SES.CMS.Module.ucSaleOff uc14ucSaleOff;
        
        /// <summary>
        /// uc11ucRightHomeAdv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucRightHomeAdv uc11ucRightHomeAdv;
        
        /// <summary>
        /// uc12Video control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucHomeVideo uc12Video;
        
        /// <summary>
        /// uc14ucThongTinDoanhNghiep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::SES.CMS.Module.ucThongTinDoanhNghiep uc14ucThongTinDoanhNghiep;
    }
}
