//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SES.CMS {
    
    
    public partial class Article {
        
        /// <summary>
        /// rptArticleDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptArticleDetail;
        
        /// <summary>
        /// ucArticleAdv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucArticleAdv ucArticleAdv1;
        
        /// <summary>
        /// ucNewArticles1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucNewArticles ucNewArticles1;
        
        /// <summary>
        /// ucLeftAdv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucLeftAdv ucLeftAdv1;
        
        /// <summary>
        /// ucRightAdv1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SES.CMS.Module.ucRightAdv ucRightAdv1;
    }
}
